### ISSUE TITLE
Tailwind classes on HTML not applied

### ISSUE THREAD

**Issue by WeAreELIC** [babycourageous/sapper-tailwind-starter#3]
The Tailwind classes that are set on HTML elements are not being applied. I just ran `npx degit babycourageous/sapper-tailwind-starter`, installed the packages via npm, then ran `npm run dev`. Any ideas?

Also, if I navigate between the pages and then refresh each page, some of the styles on elements change. For example, on the Blog page, the unordered list of blog posts will change on a refresh. Same with the paragraph text on the About page.

**Comment by babycourageous** [comment]
Oh wow - somehow the link to the Tailwind css is gone. Oops. I'm about to upload some changes that should take care of this as well as update some other old stuff.

**Comment by WeAreELIC** [comment]
Ok. I see there's a link (import) to it in the server.js file, but wasn't sure how that works.

**Comment by babycourageous** [comment]
Yeah - there should be an actual link to the generated CSS in the template. I might have lost it at some point during an update and didn't catch it.

**Comment by WeAreELIC** [comment]
FYI, I updated the template to use tailwind.css but I'm still getting that weird issue of styles not being applied when I navigate between pages and refresh them. For example, refreshing the home page, then visiting the About page and refreshing—the paragraph style changes!

Thanks!

**Comment by babycourageous** [comment]
Yeah - I'm seeing that - it's unrelated to the original issue though. For some reason the style tag styles need a refresh. Might just be a case of needing to update a lot of the tooling since it's been a minute. Investigating now.

**Comment by babycourageous** [comment]
@WeAreELIC  - 

In case you are curious: 

It took a while but I finally got this updated and hopefully solved. It stemmed from `rollup-plugin-postcss` not extracting to the `static` directory anymore due to some changes to rollup in its newest version. So instead all postcss is run through `svelte-preprocess` alone.

The initial build is noticeably longer but this seems to be the solution agreed on for now.

**Comment by WeAreELIC** [comment]
Nice! I'll probably take a look at it this week or next. Thanks for the update.
